'use client'

import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.projects': 'Projets',
    'nav.developers': 'Développeurs',
    'nav.messages': 'Messages',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.logout': 'Déconnexion',
    
    // Homepage
    'home.title.1': 'L\'AUTOMATISATION',
    'home.title.2': 'COMMENCE ICI',
    'home.subtitle': 'Connectez-vous avec les meilleurs développeurs spécialisés en IA et automatisation',
    'home.stats.devs': 'Devs',
    'home.stats.projects': 'Projets',
    'home.stats.clients': 'Clients',
    'home.cta.start.free': 'Commencer gratuitement',
    'home.cta.explore.talents': 'Explorer les talents',
    'home.cta.see.projects': 'Voir les projets',
    'home.cta.create.account.free': 'Créer mon compte gratuit',
    'home.cta.explore.developers': 'Explorer les développeurs',
    'home.cta.start.now': 'Commencer maintenant',
    'home.featured.projects': 'Projets en vedette',
    'home.featured.projects.desc': 'Découvrez les projets innovants disponibles',
    'home.budget.negotiate': 'Budget à négocier',
    'home.see.all.projects': 'Voir tous les projets',
    'home.expert.developers': 'Nos développeurs experts',
    'home.expert.developers.desc': 'Découvrez les talents qui transforment les idées',
    'home.developer': 'Développeur',
    'home.other.languages': 'autres langages',
    'home.years.experience': "années d'expérience",
    'home.developer.specialized': 'Développeur spécialisé',
    'home.see.all.developers': 'Voir tous les développeurs',
    'home.how.it.works': 'Comment ça marche ?',
    'home.how.it.works.desc': 'Connectez-vous avec les meilleurs talents en 3 étapes simples',
    'home.step.1.title': 'Créez votre profil',
    'home.step.1.desc': 'Inscrivez-vous en tant que client ou développeur et complétez votre profil',
    'home.step.2.title': 'Trouvez votre match',
    'home.step.2.desc': 'Parcourez les projets ou développeurs qui correspondent à vos besoins',
    'home.step.3.title': 'Collaborez',
    'home.step.3.desc': 'Communiquez directement et réalisez vos projets en toute sécurité',
    'home.testimonials.title': 'CE QUE DISENT NOS UTILISATEURS',
    'home.testimonials.desc': 'Découvrez les témoignages de nos utilisateurs',
    'home.testimonial.1.content': 'Grâce à LinkerAI, j\'ai trouvé le développeur parfait. 300% de ROI en 3 mois !',
    'home.testimonial.2.content': 'Une plateforme qui comprend vraiment les besoins en IA. Des clients qualifiés !',
    'home.testimonial.3.content': 'Interface intuitive, développeurs de qualité. Notre chatbot IA dépasse nos attentes !',
    'home.final.cta.title': 'PRÊT À TRANSFORMER VOTRE BUSINESS ?',
    'home.final.cta.desc': 'Rejoignez la communauté des entreprises qui ont choisi l\'excellence en IA',
    'home.example.project.1.title': 'Assistant IA pour e-commerce',
    'home.example.project.1.desc': 'Développer un chatbot intelligent',
    'home.example.project.2.title': 'Automatisation workflow RH',
    'home.example.project.2.desc': 'Automatiser les processus',
    'home.example.project.3.title': 'Analyse prédictive marketing',
    'home.example.project.3.desc': 'Créer des modèles d\'analyse',
    'home.example.dev.1.desc': 'Spécialiste IA conversationnelle',
    'home.example.dev.2.desc': 'Expert Machine Learning',
    'home.example.dev.3.desc': 'Expert Computer Vision',
    'home.experience': 'd\'expérience',
    'home.developers.count': 'développeur',
    'home.developers.available': 'disponible',
    
    // Projects
    'projects.title': 'Projets disponibles',
    'projects.subtitle': 'Découvrez les opportunités qui correspondent à vos compétences et commencez votre prochain défi',
    'projects.search': 'Rechercher des projets...',
    'projects.budget': 'Budget',
    'projects.type': 'Type de projet',
    'projects.view': 'Voir',
    'projects.create': 'Créer un projet',
    'projects.found': 'projet trouvé',
    'projects.found.plural': 'projets trouvés',
    'projects.see': 'Voir le projet',
    'projects.apply': 'Postuler',
    'projects.no.results': 'Aucun projet trouvé',
    'projects.no.results.desc': 'Essayez de modifier vos critères de recherche',
    
    // Developers
    'developers.title.1': 'NOS DÉVELOPPEURS',
    'developers.title.2': 'EXPERTS IA',
    'developers.subtitle': 'Découvrez les meilleurs talents spécialisés en intelligence artificielle et automatisation',
    'developers.search': 'Rechercher des développeurs...',
    'developers.skills': 'Compétences',
    'developers.languages': 'Langages',
    'developers.sort': 'Trier par',
    'developers.experience': "années d'expérience",
    'developers.expert': 'Expert',
    'developers.see.profile': 'Voir le profil',
    'developers.available': 'Disponible',
    'developers.busy': 'Occupé',
    'developers.unavailable': 'Indisponible',
    
    // Buttons and actions
    'btn.see': 'Voir',
    'btn.apply': 'Postuler',
    'btn.create': 'Créer',
    'btn.cancel': 'Annuler',
    'btn.save': 'Sauvegarder',
    'btn.close': 'Fermer',
    'btn.send': 'Envoyer',
    
    // Status
    'status.open': 'Ouvert',
    'status.in_progress': 'En cours',
    'status.completed': 'Terminé',
    'status.cancelled': 'Annulé',
    'status.paused': 'En pause',
    'status.pending': 'En attente',
    'status.accepted': 'Accepté',
    'status.rejected': 'Rejeté',
    
    // Forms
    'form.required': 'requis',
    'form.title': 'Titre',
    'form.description': 'Description',
    'form.budget.min': 'Budget minimum',
    'form.budget.max': 'Budget maximum',
    'form.timeline': 'Délai attendu',
    'form.complexity': 'Complexité',
    'form.skills': 'Compétences requises',
    
    // Messages
    'msg.success': 'Succès',
    'msg.error': 'Erreur',
    'msg.loading': 'Chargement...',
    'msg.no.results': 'Aucun résultat trouvé',
    
    // Time
    'time.today': 'aujourd\'hui',
    'time.day': 'j',
    'time.week': 's',
    'time.ago': 'il y a',
    
    // Messages
    'messages.loading': 'Chargement des messages...',
    'messages.login.required': 'Vous devez être connecté',
    'messages.back': 'Retour',
    'messages.conversations': 'Conversations',
    'messages.no.conversations': 'Aucune conversation',
    'messages.anonymous.user': 'Utilisateur',
    'messages.anonymous.developer': 'Développeur',
    'messages.anonymous.client': 'Client',
    'messages.general.conversation': 'Conversation générale',
    'messages.accept': 'Accepter',
    'messages.reject': 'Rejeter',
    'messages.ratings': 'avis',
    'messages.rate': 'Noter',
    'messages.no.messages': 'Aucun message dans cette conversation',
    'messages.start.conversation': 'Commencez la discussion !',
    'messages.user': 'Utilisateur',
    'messages.type.message': 'Tapez votre message...',
    'messages.select.conversation': 'Sélectionnez une conversation',
    'messages.select.conversation.desc': 'Choisissez une conversation pour commencer à discuter',
    'messages.application.accepted': 'Candidature acceptée !',
    'messages.application.accepted.desc': 'Félicitations, votre candidature a été acceptée par le client.',
    'messages.application.rejected': 'Candidature refusée.',
    'messages.application.rejected.desc': 'Votre candidature n\'a pas été retenue pour ce projet.',
    'messages.application.accepted.success': 'Candidature acceptée avec succès !',
    'messages.application.rejected.success': 'Candidature refusée avec succès !',
    
    // Dashboard
    'dashboard.not.rated.yet': 'Pas encore noté',
    'dashboard.client.title': 'Dashboard Client',
    'dashboard.client.welcome': 'Bienvenue',
    'dashboard.client.subtitle': 'Gérez vos projets et développeurs',
    'dashboard.refresh': 'Actualiser',
    'dashboard.new.project': 'Nouveau Projet',
    'dashboard.my.projects': 'Mes Projets',
    'dashboard.developers': 'Développeurs',
    'dashboard.conversations': 'Conversations',
    'dashboard.active.projects': 'Projets Actifs',
    'dashboard.view.all': 'Voir tout',
    'dashboard.no.projects': 'Aucun projet créé',
    'dashboard.no.projects.desc': 'Créez votre premier projet pour commencer à collaborer avec des développeurs',
    'dashboard.create.first.project': 'Créer mon premier projet',
    'dashboard.view.project': 'Voir le projet',
    'dashboard.edit': 'Modifier',
    'dashboard.collaborating.developers': 'Développeurs Collaborateurs',
    'dashboard.no.developers': 'Aucun développeur assigné',
    'dashboard.no.developers.desc': 'Commencez à collaborer avec des développeurs en créant un projet',
    'dashboard.explore.developers': 'Explorer les développeurs',
    'dashboard.developer': 'Développeur',
    'dashboard.years.experience': "ans d'expérience",
    'dashboard.day': 'jour',
    'dashboard.hour': 'heure',
    'dashboard.unread.messages': 'message non lu',
    'dashboard.profile': 'Profil',
    'dashboard.contact': 'Contacter',
    'dashboard.need.help': "Besoin d'aide ?",
    'dashboard.need.help.desc': 'Explorez notre plateforme pour trouver les meilleurs développeurs ou gérez vos projets existants',
    'dashboard.manage.projects': 'Gérer mes projets',
    'dashboard.my.conversations': 'Mes conversations',
    'dashboard.budget.negotiate': 'Budget à négocier',
    
    // Dashboard Developer
    'dashboard.developer.title': 'Dashboard Développeur',
    'dashboard.developer.welcome': 'Bienvenue',
    'dashboard.developer.subtitle': 'Gérez vos projets et candidatures',
    'dashboard.explore.projects': 'Explorer Projets',
    'dashboard.my.public.profile': 'Mon Profil Public',
    'dashboard.applications': 'Candidatures',
    'dashboard.rating': 'Note Moyenne',
    'dashboard.assigned.projects': 'Projets Assignés',
    'dashboard.no.assigned.projects': 'Aucun projet assigné',
    'dashboard.no.assigned.projects.desc': 'Candidatez à des projets pour commencer à collaborer avec des clients',
    'dashboard.find.projects': 'Trouver des projets',
    'dashboard.assigned': 'Assigné',
    'dashboard.created': 'Créé le',
    'dashboard.recent.applications': 'Candidatures Récentes',
    'dashboard.no.recent.applications': 'Aucune candidature récente',
    'dashboard.no.recent.applications.desc': 'Commencez à candidater aux projets qui vous intéressent',
    'dashboard.browse.projects': 'Parcourir les projets',
    'dashboard.untitled.project': 'Projet sans titre',
    'dashboard.no.description': 'Pas de description',
    'dashboard.applied': 'Candidature le',
    'dashboard.develop.career': 'Développez votre carrière !',
    'dashboard.develop.career.desc': 'Explorez de nouveaux projets, développez vos compétences et construisez votre réputation',
    'dashboard.edit.profile': 'Modifier mon profil',
    'dashboard.loading': 'Chargement du dashboard...',
    'dashboard.preparing.data': 'Préparation de vos données',
    'dashboard.loading.error': 'Erreur de chargement',
    'dashboard.retry': 'Réessayer',
    'dashboard.access.denied': 'Accès non autorisé',
    'dashboard.redirecting': 'Redirection en cours...',
    'dashboard.unknown.date': 'Date inconnue',
    'dashboard.invalid.date': 'Date invalide',
    
    // Pages profil développeur
    'profile.developer.not.found': 'Profil non trouvé',
    'profile.developer.back.to.developers': 'Retour aux développeurs',
    'profile.developer.back': 'Retour',
    'profile.developer.loading': 'Chargement du profil...',
    'profile.developer.title': 'Profil Développeur IA',
    'profile.developer.subtitle': 'Complétez votre profil pour attirer les meilleurs clients',
    'profile.developer.about': 'À propos',
    'profile.developer.daily.rate': '/jour',
    'profile.developer.experience': 'Expérience',
    'profile.developer.experience.years': "années d'expérience",
    'profile.developer.years.suffix': 'ans',
    'profile.developer.year.suffix': 'an',
    'profile.developer.skills': 'Compétences',
    'profile.developer.specializations': 'Spécialisations',
    'profile.developer.portfolio': 'Portfolio',
    'profile.developer.portfolio.github': 'GitHub',
    'profile.developer.portfolio.linkedin': 'LinkedIn',
    'profile.developer.portfolio.website': 'Site web',
    'profile.developer.contact': 'Contacter',
    'profile.developer.availability': 'Disponibilité',
    'profile.developer.available': 'Disponible',
    'profile.developer.busy': 'Occupé',
    'profile.developer.unavailable': 'Indisponible',
    'profile.developer.languages': 'Langues parlées',
    'profile.developer.location': 'Localisation',
    'profile.developer.phone': 'Téléphone',
    'profile.developer.website': 'Site web',
    'profile.developer.bio': 'Biographie',
    'profile.developer.profile.photo': 'Photo de profil',
    'profile.developer.choose.photo': 'Choisir une photo',
    'profile.developer.photo.format': 'Format JPG, PNG ou GIF.',
    'profile.developer.photo.maxSize': 'Max 5MB.',
    'profile.developer.photo.required': 'Obligatoire',
    'profile.developer.personalInfo.title': 'Informations personnelles',
    'profile.developer.personalInfo.fullName': 'Nom complet',
    'profile.developer.personalInfo.fullNamePlaceholder': 'Votre nom complet',
    'profile.developer.personalInfo.email': 'Email',
    'profile.developer.personalInfo.location': 'Localisation',
    'profile.developer.personalInfo.locationPlaceholder': 'Ville, Pays',
    'profile.developer.personalInfo.phone': 'Téléphone',
    'profile.developer.personalInfo.phonePlaceholder': '+33 6 12 34 56 78',
    'profile.developer.spokenLanguages.title': 'Langues parlées',
    'profile.developer.spokenLanguages.max': 'Max 2',
    'profile.developer.spokenLanguages.select': 'Sélectionner une langue',
    'profile.developer.spokenLanguages.add': 'Ajouter',
    'profile.developer.aiSkills.title': 'Compétences IA',
    'profile.developer.aiSkills.min': 'Min 3',
    'profile.developer.aiSkills.max': 'Max 8',
    'profile.developer.aiSkills.select': 'Sélectionner une compétence',
    'profile.developer.aiSkills.add': 'Ajouter',
    'profile.developer.aiSkills.selected': 'compétences sélectionnées',
    'profile.developer.bio.title': 'Biographie',
    'profile.developer.bio.placeholder': 'Décrivez votre expérience en IA, vos spécialités, et ce qui vous rend unique...',
    'profile.developer.bio.description': 'Présentez votre expertise en intelligence artificielle de manière engageante.',
    'profile.developer.professionalInfo.title': 'Informations professionnelles',
    'profile.developer.professionalInfo.experienceYears': "Années d'expérience",
    'profile.developer.professionalInfo.experienceYearsPlaceholder': '3',
    'profile.developer.dailyRate.title': 'Taux Journalier Moyen (TJM)',
    'profile.developer.dailyRate.undefined': 'À définir avec le client',
    'profile.developer.dailyRate.negotiable': 'négociable selon le projet',
    'profile.developer.dailyRate.placeholder': '400',
    'profile.developer.dailyRate.negotiableDescription': 'TJM à négocier selon la complexité et la durée du projet',
    'profile.developer.dailyRate.publicDisplay': 'Votre TJM sera affiché publiquement sur votre profil',
    'profile.developer.dailyRate.contactForPricing': 'Les clients pourront vous contacter pour discuter du tarif',
    'profile.developer.availability.title': 'Disponibilité',
    'profile.developer.availability.available': '🟢 Disponible',
    'profile.developer.availability.busy': '🟡 Occupé',
    'profile.developer.availability.unavailable': '🔴 Indisponible',
    'profile.developer.website.title': 'Site web / Portfolio',
    'profile.developer.website.placeholder': 'https://monportfolio.com',
    'profile.developer.save.save': 'Sauvegarder le profil',
    'profile.developer.save.saving': 'Sauvegarde en cours...',
    'profile.developer.save.newFeature': 'Nouveau :',
    'profile.developer.save.newFeatureDescription': 'Vous pouvez maintenant choisir d\'afficher votre TJM ou de le laisser "à définir" pour négocier avec chaque client.',
    'profile.developer.ratings': 'Notes et avis',
    'profile.developer.ratings.reviews': 'Notes et avis',
    'profile.developer.ratings.total': 'avis au total',
    'profile.developer.ratings.by': 'par',
    'profile.developer.ratings.anonymous': 'Client anonyme',
    'profile.developer.ratings.project': 'Projet',
    'profile.developer.ratings.no.reviews': 'Aucun avis pour le moment',
    'profile.developer.ratings.first.review': 'Soyez le premier à laisser un avis sur ce développeur',
    'profile.developer.no.reviews': 'Aucun avis pour le moment',
    'profile.developer.average.rating': 'Note moyenne',
    'profile.developer.total.projects': 'Projets réalisés',
    'profile.developer.total.reviews': 'avis',
    'profile.developer.review': 'avis',
    'profile.developer.stars': 'étoiles',
    'profile.developer.star': 'étoile',
    'profile.developer.send.message': 'Envoyer un message',
    'profile.developer.no.description': 'Aucune description fournie',
    'profile.developer.no.skills': 'Aucune compétence listée',
    'profile.developer.no.languages': 'Aucune langue spécifiée',
    'profile.developer.actions': 'Actions',
    'profile.developer.rate': 'Noter ce développeur',
    'profile.developer.edit.profile': 'Modifier mon profil',
    
    // Project Details Page
    'project.details.back.to.projects': 'Retour aux projets',
    'project.details.back': 'Retour',
    'project.details.loading': 'Chargement du projet...',
    'project.details.not.found': 'Projet non trouvé',
    'project.details.published': 'Publié le',
    'project.details.deadline': 'Échéance',
    'project.details.budget': 'Budget',
    'project.details.type': 'Type',
    'project.details.complexity': 'Complexité',
    'project.details.status': 'Statut',
    'project.details.description': 'Description',
    'project.details.client.info': 'Informations client',
    'project.details.apply': 'Postuler',
    'project.details.applied': 'Candidature envoyée',
    'project.details.login.to.apply': 'Connectez-vous pour postuler',
    'project.details.applications': 'candidatures',
    'project.details.application': 'candidature',
    'project.details.no.description': 'Aucune description fournie',

    // Project Detail Page - More specific keys
    'project.detail.title': 'Détails du Projet',
    'project.detail.subtitle': 'Découvrez tous les détails de ce projet et postulez',
    'project.detail.back.to.projects': 'Retour aux projets',
    'project.detail.not.found': 'Projet non trouvé',
    'project.detail.not.found.desc': 'Le projet que vous recherchez n\'existe pas ou a été supprimé',
    'project.detail.loading': 'Chargement du projet...',
    'project.detail.budget': 'Budget',
    'project.detail.timeline': 'Délai',
    'project.detail.posted': 'Publié le',
    'project.detail.updated': 'Mis à jour le',
    'project.detail.created': 'Créé le',
    'project.detail.progress': 'Progression',
    'project.detail.client.info': 'Informations Client',
    'project.detail.project.details': 'Détails du Projet',
    'project.detail.complexity.simple': 'Simple',
    'project.detail.complexity.medium': 'Moyen',
    'project.detail.complexity.complex': 'Complexe',
    'project.detail.type.automation': 'Automatisation',
    'project.detail.type.ai': 'Intelligence Artificielle',
    'project.detail.type.web': 'Développement Web',
    'project.detail.type.mobile': 'Application Mobile',
    'project.detail.type.data': 'Analyse de Données',
    'project.detail.type.chatbot': 'Chatbot',
    'project.detail.type.data_analysis': 'Analyse de Données',
    'project.detail.type.other': 'Autre',
    'project.detail.project.type': 'Type de projet',
    'project.detail.project.complexity': 'Complexité',
    'project.detail.project.status': 'Statut du Projet',
    'project.detail.skills.required': 'Compétences requises',
    'project.detail.skills.no.requirements': 'Aucune compétence spécifique requise',
    'project.detail.apply': 'Postuler au projet',
    'project.detail.apply.message': 'Message de candidature',
    'project.detail.apply.message.placeholder': 'Décrivez pourquoi vous êtes le bon développeur pour ce projet...',
    'project.detail.client.website': 'Site web',
    'project.detail.client.company': 'Entreprise',
    'project.detail.change.status': 'Changer le statut',
    'project.detail.status.open': 'Ouvert',
    'project.detail.status.in_progress': 'En cours',
    'project.detail.status.completed': 'Terminé',
    'project.detail.status.cancelled': 'Annulé',
    'project.detail.status.on_hold': 'En pause',
    'project.detail.status.open.desc': 'Le projet est ouvert aux candidatures',
    'project.detail.status.in_progress.desc': 'Le projet est en cours de réalisation',
    'project.detail.status.completed.desc': 'Le projet a été terminé',
    'project.detail.status.cancelled.desc': 'Le projet a été annulé',
    'project.detail.status.on_hold.desc': 'Le projet est temporairement suspendu',
    'project.detail.status.modal.title': 'Modifier le statut du projet',
    'project.detail.status.modal.current': 'Statut actuel',
    'project.detail.status.modal.new': 'Nouveau statut',
    
    // Signup/Registration Pages
    'signup.title': 'Rejoignez LinkerAI',
    'signup.create.account': 'Créez votre compte',
    'signup.complete.profile': 'Complétez votre profil développeur',
    'signup.step': 'Étape',
    'signup.user.type': 'Je suis un :',
    'signup.client.title': 'Client',
    'signup.client.description': "J'ai des projets à réaliser",
    'signup.developer.title': 'Développeur',
    'signup.developer.description': 'Je propose mes services',
    'signup.full.name': 'Nom complet',
    'signup.full.name.placeholder': 'John Doe',
    'signup.email': 'Email',
    'signup.email.placeholder': 'john@example.com',
    'signup.phone': 'Téléphone',
    'signup.phone.placeholder': '+33 6 12 34 56 78',
    'signup.password': 'Mot de passe',
    'signup.password.placeholder': '••••••••',
    'signup.continue': 'Continuer →',
    'signup.creating': 'Création...',
    'signup.create.account.button': 'Créer mon compte',
    'signup.developer.profile': 'Profil développeur',
    'signup.profile.photo': 'Photo de profil',
    'signup.upload.photo': 'Télécharger une photo',
    'signup.change.photo': 'Changer la photo',
    'signup.photo.required': '⚠️ Une photo de profil est obligatoire pour créer un compte développeur',
    'signup.professional.title': 'Titre professionnel',
    'signup.professional.title.placeholder': 'Ex: Développeur Full-Stack spécialisé IA',
    'signup.bio': 'Biographie',
    'signup.bio.placeholder': 'Présentez votre expérience, vos spécialités et ce qui vous différencie...',
    'signup.years.experience': "Années d'expérience",
    'signup.years.experience.placeholder': '5',
    'signup.daily.rate': 'Tarif journalier (€)',
    'signup.daily.rate.placeholder': '400',
    'signup.rate.to.define': 'Tarif à définir',
    'signup.skills': 'Compétences',
    'signup.skills.search': 'Rechercher une compétence...',
    'signup.specializations': 'Spécialisations',
    'signup.github.url': 'URL GitHub',
    'signup.github.placeholder': 'GitHub URL',
    'signup.linkedin.url': 'URL LinkedIn',
    'signup.linkedin.placeholder': 'LinkedIn URL',
    'signup.portfolio.url': 'URL Portfolio',
    'signup.portfolio.placeholder': 'Portfolio URL',
    'signup.create.developer.profile': 'Créer mon profil développeur',
    'signup.already.have.account': 'Déjà un compte ?',
    'signup.login.here': 'Connectez-vous ici',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.developers': 'Developers',
    'nav.messages': 'Messages',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    
    // Homepage
    'home.title.1': 'AUTOMATION',
    'home.title.2': 'STARTS HERE',
    'home.subtitle': 'Connect with the best developers specialized in AI and automation',
    'home.stats.devs': 'Devs',
    'home.stats.projects': 'Projects',
    'home.stats.clients': 'Clients',
    'home.cta.start.free': 'Start for free',
    'home.cta.explore.talents': 'Explore talents',
    'home.cta.see.projects': 'View projects',
    'home.cta.create.account.free': 'Create my free account',
    'home.cta.explore.developers': 'Explore developers',
    'home.cta.start.now': 'Start now',
    'home.featured.projects': 'Featured Projects',
    'home.featured.projects.desc': 'Discover innovative projects available',
    'home.budget.negotiate': 'Budget to negotiate',
    'home.see.all.projects': 'View all projects',
    'home.expert.developers': 'Our expert developers',
    'home.expert.developers.desc': 'Meet the talents who transform ideas',
    'home.developer': 'Developer',
    'home.other.languages': 'other languages',
    'home.years.experience': 'years of experience',
    'home.developer.specialized': 'Specialized developer',
    'home.see.all.developers': 'View all developers',
    'home.how.it.works': 'How it works?',
    'home.how.it.works.desc': 'Connect with the best talents in 3 simple steps',
    'home.step.1.title': 'Create your profile',
    'home.step.1.desc': 'Sign up as a client or developer and complete your profile',
    'home.step.2.title': 'Find your match',
    'home.step.2.desc': 'Browse projects or developers that match your needs',
    'home.step.3.title': 'Collaborate',
    'home.step.3.desc': 'Communicate directly and realize your projects safely',
    'home.testimonials.title': 'WHAT OUR USERS SAY',
    'home.testimonials.desc': 'Discover testimonials from our users',
    'home.testimonial.1.content': 'Thanks to LinkerAI, I found the perfect developer. 300% ROI in 3 months!',
    'home.testimonial.2.content': 'A platform that truly understands AI needs. Qualified clients!',
    'home.testimonial.3.content': 'Intuitive interface, quality developers. Our AI chatbot exceeds our expectations!',
    'home.final.cta.title': 'READY TO TRANSFORM YOUR BUSINESS?',
    'home.final.cta.desc': 'Join the community of companies that chose AI excellence',
    'home.example.project.1.title': 'AI Assistant for e-commerce',
    'home.example.project.1.desc': 'Develop an intelligent chatbot',
    'home.example.project.2.title': 'HR workflow automation',
    'home.example.project.2.desc': 'Automate processes',
    'home.example.project.3.title': 'Predictive marketing analysis',
    'home.example.project.3.desc': 'Create analysis models',
    'home.example.dev.1.desc': 'Conversational AI specialist',
    'home.example.dev.2.desc': 'Machine Learning expert',
    'home.example.dev.3.desc': 'Computer Vision expert',
    'home.experience': 'of experience',
    'home.developers.count': 'developer',
    'home.developers.available': 'available',
    
    // Projects
    'projects.title': 'Available Projects',
    'projects.subtitle': 'Discover opportunities that match your skills and start your next challenge',
    'projects.search': 'Search projects...',
    'projects.budget': 'Budget',
    'projects.type': 'Project type',
    'projects.view': 'View',
    'projects.create': 'Create project',
    'projects.found': 'project found',
    'projects.found.plural': 'projects found',
    'projects.see': 'View project',
    'projects.apply': 'Apply',
    'projects.no.results': 'No projects found',
    'projects.no.results.desc': 'Try modifying your search criteria',
    
    // Developers
    'developers.title.1': 'OUR DEVELOPERS',
    'developers.title.2': 'AI EXPERTS',
    'developers.subtitle': 'Discover the best talents specialized in artificial intelligence and automation',
    'developers.search': 'Search developers...',
    'developers.skills': 'Skills',
    'developers.languages': 'Languages',
    'developers.sort': 'Sort by',
    'developers.experience': 'years of experience',
    'developers.expert': 'Expert',
    'developers.see.profile': 'View profile',
    'developers.available': 'Available',
    'developers.busy': 'Busy',
    'developers.unavailable': 'Unavailable',
    
    // Buttons and actions
    'btn.see': 'View',
    'btn.apply': 'Apply',
    'btn.create': 'Create',
    'btn.cancel': 'Cancel',
    'btn.save': 'Save',
    'btn.close': 'Close',
    'btn.send': 'Send',
    
    // Status
    'status.open': 'Open',
    'status.in_progress': 'In Progress',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.paused': 'Paused',
    'status.pending': 'Pending',
    'status.accepted': 'Accepted',
    'status.rejected': 'Rejected',
    
    // Forms
    'form.required': 'required',
    'form.title': 'Title',
    'form.description': 'Description',
    'form.budget.min': 'Minimum budget',
    'form.budget.max': 'Maximum budget',
    'form.timeline': 'Expected timeline',
    'form.complexity': 'Complexity',
    'form.skills': 'Required skills',
    
    // Messages
    'msg.success': 'Success',
    'msg.error': 'Error',
    'msg.loading': 'Loading...',
    'msg.no.results': 'No results found',
    
    // Time
    'time.today': 'today',
    'time.day': 'd',
    'time.week': 'w',
    'time.ago': 'ago',
    
    // Messages
    'messages.loading': 'Loading messages...',
    'messages.login.required': 'You must be logged in',
    'messages.back': 'Back',
    'messages.conversations': 'Conversations',
    'messages.no.conversations': 'No conversations',
    'messages.anonymous.user': 'User',
    'messages.anonymous.developer': 'Developer',
    'messages.anonymous.client': 'Client',
    'messages.general.conversation': 'General conversation',
    'messages.accept': 'Accept',
    'messages.reject': 'Reject',
    'messages.ratings': 'reviews',
    'messages.rate': 'Rate',
    'messages.no.messages': 'No messages in this conversation',
    'messages.start.conversation': 'Start the discussion!',
    'messages.user': 'User',
    'messages.type.message': 'Type your message...',
    'messages.select.conversation': 'Select a conversation',
    'messages.select.conversation.desc': 'Choose a conversation to start chatting',
    'messages.application.accepted': 'Application accepted!',
    'messages.application.accepted.desc': 'Congratulations, your application has been accepted by the client.',
    'messages.application.rejected': 'Application rejected.',
    'messages.application.rejected.desc': 'Your application was not selected for this project.',
    'messages.application.accepted.success': 'Application accepted successfully!',
    'messages.application.rejected.success': 'Application rejected successfully!',
    
    // Dashboard
    'dashboard.not.rated.yet': 'Not yet rated',
    'dashboard.client.title': 'Client Dashboard',
    'dashboard.client.welcome': 'Welcome',
    'dashboard.client.subtitle': 'Manage your projects and developers',
    'dashboard.refresh': 'Refresh',
    'dashboard.new.project': 'New Project',
    'dashboard.my.projects': 'My Projects',
    'dashboard.developers': 'Developers',
    'dashboard.conversations': 'Conversations',
    'dashboard.active.projects': 'Active Projects',
    'dashboard.view.all': 'View all',
    'dashboard.no.projects': 'No projects created',
    'dashboard.no.projects.desc': 'Create your first project to start collaborating with developers',
    'dashboard.create.first.project': 'Create my first project',
    'dashboard.view.project': 'View project',
    'dashboard.edit': 'Edit',
    'dashboard.collaborating.developers': 'Collaborating Developers',
    'dashboard.no.developers': 'No developers assigned',
    'dashboard.no.developers.desc': 'Start collaborating with developers by creating a project',
    'dashboard.explore.developers': 'Explore developers',
    'dashboard.developer': 'Developer',
    'dashboard.years.experience': 'years of experience',
    'dashboard.day': 'day',
    'dashboard.hour': 'hour',
    'dashboard.unread.messages': 'unread message',
    'dashboard.profile': 'Profile',
    'dashboard.contact': 'Contact',
    'dashboard.need.help': 'Need help?',
    'dashboard.need.help.desc': 'Explore our platform to find the best developers or manage your existing projects',
    'dashboard.manage.projects': 'Manage my projects',
    'dashboard.my.conversations': 'My conversations',
    'dashboard.budget.negotiate': 'Budget to negotiate',
    
    // Dashboard Developer
    'dashboard.developer.title': 'Developer Dashboard',
    'dashboard.developer.welcome': 'Welcome',
    'dashboard.developer.subtitle': 'Manage your projects and applications',
    'dashboard.explore.projects': 'Explore Projects',
    'dashboard.my.public.profile': 'My Public Profile',
    'dashboard.applications': 'Applications',
    'dashboard.rating': 'Average Rating',
    'dashboard.assigned.projects': 'Assigned Projects',
    'dashboard.no.assigned.projects': 'No assigned projects',
    'dashboard.no.assigned.projects.desc': 'Apply to projects to start collaborating with clients',
    'dashboard.find.projects': 'Find projects',
    'dashboard.assigned': 'Assigned',
    'dashboard.created': 'Created',
    'dashboard.recent.applications': 'Recent Applications',
    'dashboard.no.recent.applications': 'No recent applications',
    'dashboard.no.recent.applications.desc': 'Start applying to projects that interest you',
    'dashboard.browse.projects': 'Browse projects',
    'dashboard.untitled.project': 'Untitled project',
    'dashboard.no.description': 'No description',
    'dashboard.applied': 'Applied on',
    'dashboard.develop.career': 'Develop your career!',
    'dashboard.develop.career.desc': 'Explore new projects, develop your skills and build your reputation',
    'dashboard.edit.profile': 'Edit my profile',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.preparing.data': 'Preparing your data',
    'dashboard.loading.error': 'Loading error',
    'dashboard.retry': 'Retry',
    'dashboard.access.denied': 'Access denied',
    'dashboard.redirecting': 'Redirecting...',
    'dashboard.unknown.date': 'Unknown date',
    'dashboard.invalid.date': 'Invalid date',
    
    // Developer profile pages
    'profile.developer.not.found': 'Profile not found',
    'profile.developer.back.to.developers': 'Back to developers',
    'profile.developer.back': 'Back',
    'profile.developer.loading': 'Loading profile...',
    'profile.developer.title': 'AI Developer Profile',
    'profile.developer.subtitle': 'Complete your profile to attract the best clients',
    'profile.developer.about': 'About',
    'profile.developer.daily.rate': '/day',
    'profile.developer.experience': 'Experience',
    'profile.developer.experience.years': 'years of experience',
    'profile.developer.years.suffix': 'years',
    'profile.developer.year.suffix': 'year',
    'profile.developer.skills': 'Skills',
    'profile.developer.specializations': 'Specializations',
    'profile.developer.portfolio': 'Portfolio',
    'profile.developer.portfolio.github': 'GitHub',
    'profile.developer.portfolio.linkedin': 'LinkedIn',
    'profile.developer.portfolio.website': 'Website',
    'profile.developer.contact': 'Contact',
    'profile.developer.availability': 'Availability',
    'profile.developer.available': 'Available',
    'profile.developer.busy': 'Busy',
    'profile.developer.unavailable': 'Unavailable',
    'profile.developer.languages': 'Spoken Languages',
    'profile.developer.location': 'Location',
    'profile.developer.phone': 'Phone',
    'profile.developer.website': 'Website',
    'profile.developer.bio': 'Biography',
    'profile.developer.profile.photo': 'Profile Photo',
    'profile.developer.choose.photo': 'Choose a photo',
    'profile.developer.photo.format': 'JPG, PNG or GIF format.',
    'profile.developer.photo.maxSize': 'Max 5MB.',
    'profile.developer.photo.required': 'Required',
    'profile.developer.personalInfo.title': 'Personal Information',
    'profile.developer.personalInfo.fullName': 'Full Name',
    'profile.developer.personalInfo.fullNamePlaceholder': 'Your full name',
    'profile.developer.personalInfo.email': 'Email',
    'profile.developer.personalInfo.location': 'Location',
    'profile.developer.personalInfo.locationPlaceholder': 'City, Country',
    'profile.developer.personalInfo.phone': 'Phone',
    'profile.developer.personalInfo.phonePlaceholder': '+1 555 123 4567',
    'profile.developer.spokenLanguages.title': 'Spoken Languages',
    'profile.developer.spokenLanguages.max': 'Max 2',
    'profile.developer.spokenLanguages.select': 'Select a language',
    'profile.developer.spokenLanguages.add': 'Add',
    'profile.developer.aiSkills.title': 'AI Skills',
    'profile.developer.aiSkills.min': 'Min 3',
    'profile.developer.aiSkills.max': 'Max 8',
    'profile.developer.aiSkills.select': 'Select a skill',
    'profile.developer.aiSkills.add': 'Add',
    'profile.developer.aiSkills.selected': 'skills selected',
    'profile.developer.bio.title': 'Biography',
    'profile.developer.bio.placeholder': 'Describe your AI experience, your specialties, and what makes you unique...',
    'profile.developer.bio.description': 'Present your artificial intelligence expertise in an engaging way.',
    'profile.developer.professionalInfo.title': 'Professional Information',
    'profile.developer.professionalInfo.experienceYears': 'Years of Experience',
    'profile.developer.professionalInfo.experienceYearsPlaceholder': '3',
    'profile.developer.dailyRate.title': 'Daily Rate (TJM)',
    'profile.developer.dailyRate.undefined': 'To be defined with client',
    'profile.developer.dailyRate.negotiable': 'negotiable per project',
    'profile.developer.dailyRate.placeholder': '400',
    'profile.developer.dailyRate.negotiableDescription': 'Daily rate negotiable based on complexity and project duration',
    'profile.developer.dailyRate.publicDisplay': 'Your daily rate will be publicly displayed on your profile',
    'profile.developer.dailyRate.contactForPricing': 'Clients can contact you to discuss pricing',
    'profile.developer.availability.title': 'Availability',
    'profile.developer.availability.available': '🟢 Available',
    'profile.developer.availability.busy': '🟡 Busy',
    'profile.developer.availability.unavailable': '🔴 Unavailable',
    'profile.developer.website.title': 'Website / Portfolio',
    'profile.developer.website.placeholder': 'https://myportfolio.com',
    'profile.developer.save.save': 'Save Profile',
    'profile.developer.save.saving': 'Saving...',
    'profile.developer.save.newFeature': 'New:',
    'profile.developer.save.newFeatureDescription': 'You can now choose to display your daily rate or leave it "to be defined" to negotiate with each client.',
    'profile.developer.ratings': 'Ratings and reviews',
    'profile.developer.ratings.reviews': 'Ratings and reviews',
    'profile.developer.ratings.total': 'total reviews',
    'profile.developer.ratings.by': 'by',
    'profile.developer.ratings.anonymous': 'Anonymous client',
    'profile.developer.ratings.project': 'Project',
    'profile.developer.ratings.no.reviews': 'No reviews yet',
    'profile.developer.ratings.first.review': 'Be the first to review this developer',
    'profile.developer.no.reviews': 'No reviews yet',
    'profile.developer.average.rating': 'Average rating',
    'profile.developer.total.projects': 'Projects completed',
    'profile.developer.total.reviews': 'reviews',
    'profile.developer.review': 'review',
    'profile.developer.stars': 'stars',
    'profile.developer.star': 'star',
    'profile.developer.send.message': 'Send message',
    'profile.developer.no.description': 'No description provided',
    'profile.developer.no.skills': 'No skills listed',
    'profile.developer.no.languages': 'No languages specified',
    'profile.developer.actions': 'Actions',
    'profile.developer.rate': 'Rate this developer',
    'profile.developer.edit.profile': 'Edit my profile',
    
    // Project Details Page
    'project.details.back.to.projects': 'Back to projects',
    'project.details.back': 'Back',
    'project.details.loading': 'Loading project...',
    'project.details.not.found': 'Project not found',
    'project.details.published': 'Published on',
    'project.details.deadline': 'Deadline',
    'project.details.budget': 'Budget',
    'project.details.type': 'Type',
    'project.details.complexity': 'Complexity',
    'project.details.status': 'Status',
    'project.details.description': 'Description',
    'project.details.client.info': 'Client information',
    'project.details.apply': 'Apply',
    'project.details.applied': 'Application sent',
    'project.details.login.to.apply': 'Login to apply',
    'project.details.applications': 'applications',
    'project.details.application': 'application',
    'project.details.no.description': 'No description provided',

    // Project Detail Page - More specific keys
    'project.detail.title': 'Project Details',
    'project.detail.subtitle': 'Discover all the details of this project and apply',
    'project.detail.back.to.projects': 'Back to projects',
    'project.detail.not.found': 'Project not found',
    'project.detail.not.found.desc': 'The project you are looking for does not exist or has been deleted',
    'project.detail.loading': 'Loading project...',
    'project.detail.budget': 'Budget',
    'project.detail.timeline': 'Timeline',
    'project.detail.posted': 'Posted on',
    'project.detail.updated': 'Updated on',
    'project.detail.created': 'Created on',
    'project.detail.progress': 'Progress',
    'project.detail.client.info': 'Client Information',
    'project.detail.project.details': 'Project Details',
    'project.detail.complexity.simple': 'Simple',
    'project.detail.complexity.medium': 'Medium',
    'project.detail.complexity.complex': 'Complex',
    'project.detail.type.automation': 'Automation',
    'project.detail.type.ai': 'Artificial Intelligence',
    'project.detail.type.web': 'Web Development',
    'project.detail.type.mobile': 'Mobile Application',
    'project.detail.type.data': 'Data Analysis',
    'project.detail.type.chatbot': 'Chatbot',
    'project.detail.type.data_analysis': 'Data Analysis',
    'project.detail.type.other': 'Other',
    'project.detail.project.type': 'Project type',
    'project.detail.project.complexity': 'Complexity',
    'project.detail.project.status': 'Project Status',
    'project.detail.skills.required': 'Required skills',
    'project.detail.skills.no.requirements': 'No specific skills required',
    'project.detail.apply': 'Apply to project',
    'project.detail.apply.message': 'Application message',
    'project.detail.apply.message.placeholder': 'Describe why you are the right developer for this project...',
    'project.detail.client.website': 'Website',
    'project.detail.client.company': 'Company',
    'project.detail.change.status': 'Change status',
    'project.detail.status.open': 'Open',
    'project.detail.status.in_progress': 'In Progress',
    'project.detail.status.completed': 'Completed',
    'project.detail.status.cancelled': 'Cancelled',
    'project.detail.status.on_hold': 'On Hold',
    'project.detail.status.open.desc': 'The project is open for applications',
    'project.detail.status.in_progress.desc': 'The project is being worked on',
    'project.detail.status.completed.desc': 'The project has been completed',
    'project.detail.status.cancelled.desc': 'The project has been cancelled',
    'project.detail.status.on_hold.desc': 'The project is temporarily suspended',
    'project.detail.status.modal.title': 'Change project status',
    'project.detail.status.modal.current': 'Current status',
    'project.detail.status.modal.new': 'New status',
    
    // Signup/Registration Pages
    'signup.title': 'Join LinkerAI',
    'signup.create.account': 'Create your account',
    'signup.complete.profile': 'Complete your developer profile',
    'signup.step': 'Step',
    'signup.user.type': 'I am a:',
    'signup.client.title': 'Client',
    'signup.client.description': 'I have projects to realize',
    'signup.developer.title': 'Developer',
    'signup.developer.description': 'I offer my services',
    'signup.full.name': 'Full name',
    'signup.full.name.placeholder': 'John Doe',
    'signup.email': 'Email',
    'signup.email.placeholder': 'john@example.com',
    'signup.phone': 'Phone',
    'signup.phone.placeholder': '+33 6 12 34 56 78',
    'signup.password': 'Password',
    'signup.password.placeholder': '••••••••',
    'signup.continue': 'Continue →',
    'signup.creating': 'Creating...',
    'signup.create.account.button': 'Create my account',
    'signup.developer.profile': 'Developer profile',
    'signup.profile.photo': 'Profile photo',
    'signup.upload.photo': 'Upload photo',
    'signup.change.photo': 'Change photo',
    'signup.photo.required': '⚠️ A profile photo is required to create a developer account',
    'signup.professional.title': 'Professional title',
    'signup.professional.title.placeholder': 'Ex: Full-Stack Developer specialized in AI',
    'signup.bio': 'Biography',
    'signup.bio.placeholder': 'Present your experience, your specialties and what sets you apart...',
    'signup.years.experience': 'Years of experience',
    'signup.years.experience.placeholder': '5',
    'signup.daily.rate': 'Daily rate (€)',
    'signup.daily.rate.placeholder': '400',
    'signup.rate.to.define': 'Rate to be defined',
    'signup.skills': 'Skills',
    'signup.skills.search': 'Search for a skill...',
    'signup.specializations': 'Specializations',
    'signup.github.url': 'GitHub URL',
    'signup.github.placeholder': 'GitHub URL',
    'signup.linkedin.url': 'LinkedIn URL',
    'signup.linkedin.placeholder': 'LinkedIn URL',
    'signup.portfolio.url': 'Portfolio URL',
    'signup.portfolio.placeholder': 'Portfolio URL',
    'signup.create.developer.profile': 'Create my developer profile',
    'signup.already.have.account': 'Already have an account?',
    'signup.login.here': 'Login here',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language')
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  // Fonction de traduction
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 