'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Traductions
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.projects': 'Projets',
    'nav.developers': 'Développeurs',
    'nav.messages': 'Messages',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Connexion',
    'nav.signup': "S'inscrire",
    'nav.logout': 'Déconnexion',
    
    // Page d'accueil
    'home.title.1': "L'AUTOMATISATION",
    'home.title.2': 'COMMENCE ICI',
    'home.subtitle': 'Connectez-vous avec les meilleurs développeurs spécialisés en IA et automatisation',
    'home.stats.devs': 'Devs',
    'home.stats.projects': 'Projets',
    'home.stats.clients': 'Clients',
    'home.cta.start.free': 'Commencer gratuitement',
    'home.cta.explore.talents': 'Explorer les talents',
    'home.cta.see.projects': 'Voir les projets',
    'home.cta.create.account.free': 'Créer mon compte gratuitement',
    'home.cta.explore.developers': 'Explorer les développeurs',
    'home.cta.start.now': 'Commencer maintenant',
    'home.featured.projects': 'Projets en vedette',
    'home.featured.projects.desc': 'Découvrez les projets innovants disponibles',
    'home.budget.negotiate': 'Budget à négocier',
    'home.see.all.projects': 'Voir tous les projets',
    'home.expert.developers': 'Nos développeurs experts',
    'home.expert.developers.desc': 'Rencontrez les talents qui transforment les idées',
    'home.developer': 'Développeur',
    'home.other.languages': 'autres langues',
    'home.years.experience': "ans d'expérience",
    'home.developer.specialized': 'Développeur spécialisé',
    'home.see.all.developers': 'Voir tous les développeurs',
    'home.how.it.works': 'Comment ça marche ?',
    'home.how.it.works.desc': 'Connectez-vous avec les meilleurs talents en 3 étapes simples',
    'home.step.1.title': 'Créez votre profil',
    'home.step.1.desc': 'Inscrivez-vous en tant que client ou développeur et complétez votre profil',
    'home.step.2.title': 'Trouvez votre match',
    'home.step.2.desc': 'Parcourez les projets ou développeurs qui correspondent à vos besoins',
    'home.step.3.title': 'Collaborez',
    'home.step.3.desc': 'Communiquez directement et réalisez vos projets en toute sécurité',
    'home.testimonials.title': 'CE QUE DISENT NOS UTILISATEURS',
    'home.testimonials.desc': 'Découvrez les témoignages de nos utilisateurs',
    'home.testimonial.1.content': "Grâce à LinkerAI, j'ai trouvé le développeur parfait. ROI de 300% en 3 mois !",
    'home.testimonial.2.content': 'Une plateforme qui comprend vraiment les besoins en IA. Des clients qualifiés !',
    'home.testimonial.3.content': 'Interface intuitive, développeurs de qualité. Notre chatbot IA dépasse nos attentes !',
    'home.final.cta.title': 'PRÊT À TRANSFORMER VOTRE BUSINESS ?',
    'home.final.cta.desc': "Rejoignez la communauté des entreprises qui ont choisi l'excellence en IA",
    'home.example.project.1.title': 'Assistant IA pour e-commerce',
    'home.example.project.1.desc': 'Développer un chatbot intelligent',
    'home.example.project.2.title': 'Automatisation workflow RH',
    'home.example.project.2.desc': 'Automatiser les processus',
    'home.example.project.3.title': 'Analyse prédictive marketing',
    'home.example.project.3.desc': 'Créer des modèles d\'analyse',
    'home.example.dev.1.desc': 'Spécialiste IA conversationnelle',
    'home.example.dev.2.desc': 'Experte Machine Learning',
    'home.example.dev.3.desc': 'Experte Computer Vision',
    'home.experience': "d'expérience",
    'home.developers.count': 'développeur',
    'home.developers.available': 'disponible',
    
    // Projets
    'projects.title': 'Projets Disponibles',
    'projects.subtitle': 'Découvrez les opportunités qui correspondent à vos compétences et commencez votre prochain défi',
    'projects.search': 'Rechercher des projets...',
    'projects.budget': 'Budget',
    'projects.type': 'Type de projet',
    'projects.view': 'Affichage',
    'projects.create': 'Créer un projet',
    'projects.found': 'projet trouvé',
    'projects.found.plural': 'projets trouvés',
    'projects.see': 'Voir le projet',
    'projects.apply': 'Candidater',
    'projects.no.results': 'Aucun projet trouvé',
    'projects.no.results.desc': 'Essayez de modifier vos critères de recherche',
    
    // Développeurs
    'developers.title.1': 'NOS DÉVELOPPEURS',
    'developers.title.2': 'EXPERTS EN IA',
    'developers.subtitle': 'Découvrez les meilleurs talents spécialisés en intelligence artificielle et automatisation',
    'developers.search': 'Rechercher des développeurs...',
    'developers.skills': 'Compétences',
    'developers.languages': 'Langues',
    'developers.sort': 'Trier par',
    'developers.experience': 'ans d\'expérience',
    'developers.expert': 'Expert',
    'developers.see.profile': 'Voir le profil',
    'developers.available': 'Disponible',
    'developers.busy': 'Occupé',
    'developers.unavailable': 'Non disponible',
    
    // Boutons et actions
    'btn.see': 'Voir',
    'btn.apply': 'Candidater',
    'btn.create': 'Créer',
    'btn.cancel': 'Annuler',
    'btn.save': 'Enregistrer',
    'btn.close': 'Fermer',
    'btn.send': 'Envoyer',
    
    // Status
    'status.open': 'Ouvert',
    'status.in_progress': 'En cours',
    'status.completed': 'Terminé',
    'status.cancelled': 'Annulé',
    'status.paused': 'En pause',
    'status.pending': 'En attente',
    'status.accepted': 'Accepté',
    'status.rejected': 'Refusé',
    
    // Formulaires
    'form.required': 'obligatoire',
    'form.title': 'Titre',
    'form.description': 'Description',
    'form.budget.min': 'Budget minimum',
    'form.budget.max': 'Budget maximum',
    'form.timeline': 'Délai souhaité',
    'form.complexity': 'Complexité',
    'form.skills': 'Compétences requises',
    
    // Messages
    'msg.success': 'Succès',
    'msg.error': 'Erreur',
    'msg.loading': 'Chargement...',
    'msg.no.results': 'Aucun résultat trouvé',
    
    // Time
    'time.today': "aujourd'hui",
    'time.day': 'j',
    'time.week': 's',
    'time.ago': 'il y a',
    
    // Messages
    'messages.loading': 'Chargement des messages...',
    'messages.login.required': 'Vous devez être connecté',
    'messages.back': 'Retour',
    'messages.conversations': 'Conversations',
    'messages.no.conversations': 'Aucune conversation',
    'messages.anonymous.user': 'Utilisateur',
    'messages.anonymous.developer': 'Développeur',
    'messages.anonymous.client': 'Client',
    'messages.general.conversation': 'Conversation générale',
    'messages.accept': 'Accepter',
    'messages.reject': 'Refuser',
    'messages.ratings': 'avis',
    'messages.rate': 'Noter',
    'messages.no.messages': 'Aucun message dans cette conversation',
    'messages.start.conversation': 'Commencez la discussion !',
    'messages.user': 'Utilisateur',
    'messages.type.message': 'Tapez votre message...',
    'messages.select.conversation': 'Sélectionnez une conversation',
    'messages.select.conversation.desc': 'Choisissez une conversation pour commencer à échanger',
    'messages.application.accepted': 'Candidature acceptée !',
    'messages.application.accepted.desc': 'Félicitations, votre candidature a été acceptée par le client.',
    'messages.application.rejected': 'Candidature refusée.',
    'messages.application.rejected.desc': "Votre candidature n'a pas été retenue pour ce projet.",
    'messages.application.accepted.success': 'Candidature acceptée avec succès !',
    'messages.application.rejected.success': 'Candidature refusée avec succès !',
    
    // Dashboard
    'dashboard.not.rated.yet': 'Pas encore noté',
    'dashboard.client.title': 'Dashboard Client',
    'dashboard.client.welcome': 'Bienvenue',
    'dashboard.client.subtitle': 'Gérez vos projets et développeurs',
    'dashboard.refresh': 'Rafraîchir',
    'dashboard.new.project': 'Nouveau Projet',
    'dashboard.my.projects': 'Mes Projets',
    'dashboard.developers': 'Développeurs',
    'dashboard.conversations': 'Conversations',
    'dashboard.active.projects': 'Projets actifs',
    'dashboard.view.all': 'Voir tous',
    'dashboard.no.projects': 'Aucun projet créé',
    'dashboard.no.projects.desc': 'Créez votre premier projet pour commencer à collaborer avec des développeurs',
    'dashboard.create.first.project': 'Créer mon premier projet',
    'dashboard.view.project': 'Voir le projet',
    'dashboard.edit': 'Modifier',
    'dashboard.collaborating.developers': 'Développeurs Collaborateurs',
    'dashboard.no.developers': 'Aucun développeur assigné',
    'dashboard.no.developers.desc': 'Commencez à collaborer avec des développeurs en créant un projet',
    'dashboard.explore.developers': 'Explorer les développeurs',
    'dashboard.developer': 'Développeur',
    'dashboard.years.experience': "ans d'expérience",
    'dashboard.day': 'jour',
    'dashboard.hour': 'heure',
    'dashboard.unread.messages': 'message non lu|messages non lus',
    'dashboard.profile': 'Profil',
    'dashboard.contact': 'Contacter',
    'dashboard.need.help': "Besoin d'aide ?",
    'dashboard.need.help.desc': 'Explorez notre plateforme pour trouver les meilleurs développeurs ou gérez vos projets existants',
    'dashboard.manage.projects': 'Gérer mes projets',
    'dashboard.my.conversations': 'Mes conversations',
    'dashboard.budget.negotiate': 'Budget à négocier',
    
    // Dashboard Developer
    'dashboard.developer.title': 'Dashboard Développeur',
    'dashboard.developer.welcome': 'Bienvenue',
    'dashboard.developer.subtitle': 'Gérez vos projets et candidatures',
    'dashboard.explore.projects': 'Explorer Projets',
    'dashboard.my.public.profile': 'Mon Profil Public',
    'dashboard.applications': 'Candidatures',
    'dashboard.rating': 'Note Moyenne',
    'dashboard.assigned.projects': 'Projets Assignés',
    'dashboard.no.assigned.projects': 'Aucun projet assigné',
    'dashboard.no.assigned.projects.desc': 'Candidatez à des projets pour commencer à collaborer avec des clients',
    'dashboard.find.projects': 'Trouver des projets',
    'dashboard.assigned': 'Assigné',
    'dashboard.created': 'Créé le',
    'dashboard.my.applications': 'Mes Candidatures',
    'dashboard.no.applications': 'Aucune candidature',
    'dashboard.no.applications.desc': 'Commencez à candidater aux projets qui vous intéressent',
    'dashboard.view.available.projects': 'Voir les projets disponibles',
    'dashboard.untitled.project': 'Projet sans titre',
    'dashboard.no.description': 'Pas de description',
    'dashboard.applied.on': 'Candidature le',
    'dashboard.develop.career': 'Développez votre carrière !',
    'dashboard.develop.career.desc': 'Explorez de nouveaux projets, développez vos compétences et construisez votre réputation',
    'dashboard.edit.profile': 'Modifier mon profil',
    'dashboard.loading': 'Chargement du dashboard...',
    'dashboard.preparing.data': 'Préparation de vos données',
    'dashboard.loading.error': 'Erreur de chargement',
    'dashboard.retry': 'Réessayer',
    'dashboard.access.denied': 'Accès non autorisé',
    'dashboard.redirecting': 'Redirection en cours...',
    'dashboard.unknown.date': 'Date inconnue',
    'dashboard.invalid.date': 'Date invalide',
    
    // Pages profil développeur
    'profile.developer.not.found': 'Profil non trouvé',
    'profile.developer.back.to.developers': 'Retour aux développeurs',
    'profile.developer.back': 'Retour',
    'profile.developer.loading': 'Chargement du profil...',
    'profile.developer.daily.rate': '/jour',
    'profile.developer.hourly.rate': '/h',
    'profile.developer.contact.info': 'Informations de contact',
    'profile.developer.location': 'Localisation',
    'profile.developer.email': 'Email',
    'profile.developer.phone': 'Téléphone',
    'profile.developer.website': 'Site web',
    'profile.developer.experience': 'Expérience',
    'profile.developer.experience.years': "ans d'expérience",
    'profile.developer.availability': 'Disponibilité',
    'profile.developer.availability.available': 'Disponible',
    'profile.developer.availability.busy': 'Occupé',
    'profile.developer.availability.unavailable': 'Non disponible',
    'profile.developer.timezone': 'Fuseau horaire',
    'profile.developer.actions': 'Actions',
    'profile.developer.contact': 'Contacter',
    'profile.developer.rate': 'Noter',
    'profile.developer.edit.profile': 'Modifier le profil',
    'profile.developer.about': 'À propos',
    'profile.developer.no.description': 'Aucune description disponible pour le moment.',
    'profile.developer.skills': 'Compétences',
    'profile.developer.no.skills': 'Aucune compétence renseignée pour le moment.',
    'profile.developer.languages': 'Langues',
    'profile.developer.no.languages': 'Aucune langue renseignée pour le moment.',
    'profile.developer.portfolio': 'Portfolio & Liens',
    'profile.developer.portfolio.github': 'GitHub',
    'profile.developer.portfolio.linkedin': 'LinkedIn',
    'profile.developer.portfolio.website': 'Site personnel',
    'profile.developer.ratings.reviews': 'Avis & Évaluations',
    'profile.developer.ratings.average': 'Note moyenne',
    'profile.developer.ratings.total': 'avis au total',
    'profile.developer.ratings.no.reviews': 'Aucun avis pour le moment',
    'profile.developer.ratings.first.review': 'Soyez le premier à laisser un avis !',
    'profile.developer.ratings.project': 'Projet',
    'profile.developer.ratings.by': 'par',
    'profile.developer.ratings.anonymous': 'Client anonyme',
    
    // Pages détail projet
    'project.detail.not.found': 'Projet non trouvé',
    'project.detail.not.found.desc': "Ce projet n'existe pas ou a été supprimé.",
    'project.detail.back.to.projects': 'Retour aux projets',
    'project.detail.title': 'Détails du Projet',
    'project.detail.subtitle': 'Découvrez tous les détails de ce projet et candidatez si il correspond à vos compétences',
    'project.detail.change.status': 'Changer le statut',
    'project.detail.type.automation': 'Automation',
    'project.detail.type.ai': 'Intelligence Artificielle',
    'project.detail.type.chatbot': 'Chatbot',
    'project.detail.type.data_analysis': 'Analyse de données',
    'project.detail.type.other': 'Autre',
    'project.detail.complexity.simple': 'Simple',
    'project.detail.complexity.medium': 'Moyen',
    'project.detail.complexity.complex': 'Complexe',
    'project.detail.client.info': 'Informations client',
    'project.detail.client.anonymous': 'Client anonyme',
    'project.detail.client.company': 'Entreprise',
    'project.detail.client.industry': "Secteur d'activité",
    'project.detail.client.company.size': "Taille de l'entreprise",
    'project.detail.client.website': 'Site web',
    'project.detail.project.details': 'Détails du projet',
    'project.detail.project.type': 'Type de projet',
    'project.detail.project.complexity': 'Complexité',
    'project.detail.project.status': 'Statut',
    'project.detail.budget': 'Budget',
    'project.detail.timeline': 'Délai',
    'project.detail.posted': 'Publié le',
    'project.detail.updated': 'Mis à jour le',
    'project.detail.skills.required': 'Compétences requises',
    'project.detail.skills.no.requirements': 'Aucune compétence spécifique requise',
    'project.detail.apply': 'Candidater',
    'project.detail.apply.message': 'Message de candidature',
    'project.detail.apply.message.placeholder': 'Présentez-vous et expliquez pourquoi vous êtes le candidat idéal pour ce projet...',
    'project.detail.apply.submit': 'Envoyer ma candidature',
    'project.detail.apply.success': 'Candidature envoyée avec succès !',
    'project.detail.apply.already.applied': 'Vous avez déjà candidaté',
    'project.detail.apply.already.applied.desc': 'Vous avez déjà envoyé une candidature pour ce projet.',
    'project.detail.apply.status.pending': 'Votre candidature est en attente de réponse.',
    'project.detail.apply.status.accepted': 'Félicitations ! Votre candidature a été acceptée.',
    'project.detail.apply.status.rejected': 'Votre candidature a été refusée.',
    'project.detail.login.required': 'Connexion requise',
    'project.detail.login.required.desc': 'Vous devez vous connecter pour candidater à ce projet.',
    'project.detail.login': 'Se connecter',
    'project.detail.client.only': 'Réservé aux clients',
    'project.detail.client.only.desc': 'Seuls les développeurs peuvent candidater à des projets.',
    'project.detail.own.project': 'Votre projet',
    'project.detail.own.project.desc': 'Vous ne pouvez pas candidater à votre propre projet.',
    'project.detail.status.modal.title': 'Changer le statut du projet',
    'project.detail.status.modal.current': 'Statut actuel',
    'project.detail.status.modal.new': 'Nouveau statut',
    'project.detail.status.modal.save': 'Mettre à jour',
    'project.detail.status.modal.cancel': 'Annuler',
    'project.detail.status.open': 'Ouvert',
    'project.detail.status.open.desc': 'Le projet est ouvert aux candidatures',
    'project.detail.status.in_progress': 'En cours',
    'project.detail.status.in_progress.desc': 'Le projet est en cours de développement',
    'project.detail.status.completed': 'Terminé',
    'project.detail.status.completed.desc': 'Le projet a été terminé avec succès',
    'project.detail.status.cancelled': 'Annulé',
    'project.detail.status.cancelled.desc': 'Le projet a été annulé',
    'project.detail.status.on_hold': 'En pause',
    'project.detail.status.on_hold.desc': 'Le projet est temporairement en pause',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.developers': 'Developers',
    'nav.messages': 'Messages',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    
    // Homepage
    'home.title.1': 'AUTOMATION',
    'home.title.2': 'STARTS HERE',
    'home.subtitle': 'Connect with the best developers specialized in AI and automation',
    'home.stats.devs': 'Devs',
    'home.stats.projects': 'Projects',
    'home.stats.clients': 'Clients',
    'home.cta.start.free': 'Start for free',
    'home.cta.explore.talents': 'Explore talents',
    'home.cta.see.projects': 'View projects',
    'home.cta.create.account.free': 'Create my free account',
    'home.cta.explore.developers': 'Explore developers',
    'home.cta.start.now': 'Start now',
    'home.featured.projects': 'Featured Projects',
    'home.featured.projects.desc': 'Discover innovative projects available',
    'home.budget.negotiate': 'Budget to negotiate',
    'home.see.all.projects': 'View all projects',
    'home.expert.developers': 'Our expert developers',
    'home.expert.developers.desc': 'Meet the talents who transform ideas',
    'home.developer': 'Developer',
    'home.other.languages': 'other languages',
    'home.years.experience': 'years of experience',
    'home.developer.specialized': 'Specialized developer',
    'home.see.all.developers': 'View all developers',
    'home.how.it.works': 'How it works?',
    'home.how.it.works.desc': 'Connect with the best talents in 3 simple steps',
    'home.step.1.title': 'Create your profile',
    'home.step.1.desc': 'Sign up as a client or developer and complete your profile',
    'home.step.2.title': 'Find your match',
    'home.step.2.desc': 'Browse projects or developers that match your needs',
    'home.step.3.title': 'Collaborate',
    'home.step.3.desc': 'Communicate directly and realize your projects safely',
    'home.testimonials.title': 'WHAT OUR USERS SAY',
    'home.testimonials.desc': 'Discover testimonials from our users',
    'home.testimonial.1.content': 'Thanks to LinkerAI, I found the perfect developer. 300% ROI in 3 months!',
    'home.testimonial.2.content': 'A platform that truly understands AI needs. Qualified clients!',
    'home.testimonial.3.content': 'Intuitive interface, quality developers. Our AI chatbot exceeds our expectations!',
    'home.final.cta.title': 'READY TO TRANSFORM YOUR BUSINESS?',
    'home.final.cta.desc': 'Join the community of companies that chose AI excellence',
    'home.example.project.1.title': 'AI Assistant for e-commerce',
    'home.example.project.1.desc': 'Develop an intelligent chatbot',
    'home.example.project.2.title': 'HR workflow automation',
    'home.example.project.2.desc': 'Automate processes',
    'home.example.project.3.title': 'Predictive marketing analysis',
    'home.example.project.3.desc': 'Create analysis models',
    'home.example.dev.1.desc': 'Conversational AI specialist',
    'home.example.dev.2.desc': 'Machine Learning expert',
    'home.example.dev.3.desc': 'Computer Vision expert',
    'home.experience': 'of experience',
    'home.developers.count': 'developer',
    'home.developers.available': 'available',
    
    // Projects
    'projects.title': 'Available Projects',
    'projects.subtitle': 'Discover opportunities that match your skills and start your next challenge',
    'projects.search': 'Search projects...',
    'projects.budget': 'Budget',
    'projects.type': 'Project type',
    'projects.view': 'View',
    'projects.create': 'Create project',
    'projects.found': 'project found',
    'projects.found.plural': 'projects found',
    'projects.see': 'View project',
    'projects.apply': 'Apply',
    'projects.no.results': 'No projects found',
    'projects.no.results.desc': 'Try modifying your search criteria',
    
    // Developers
    'developers.title.1': 'OUR DEVELOPERS',
    'developers.title.2': 'AI EXPERTS',
    'developers.subtitle': 'Discover the best talents specialized in artificial intelligence and automation',
    'developers.search': 'Search developers...',
    'developers.skills': 'Skills',
    'developers.languages': 'Languages',
    'developers.sort': 'Sort by',
    'developers.experience': 'years of experience',
    'developers.expert': 'Expert',
    'developers.see.profile': 'View profile',
    'developers.available': 'Available',
    'developers.busy': 'Busy',
    'developers.unavailable': 'Unavailable',
    
    // Buttons and actions
    'btn.see': 'View',
    'btn.apply': 'Apply',
    'btn.create': 'Create',
    'btn.cancel': 'Cancel',
    'btn.save': 'Save',
    'btn.close': 'Close',
    'btn.send': 'Send',
    
    // Status
    'status.open': 'Open',
    'status.in_progress': 'In Progress',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.paused': 'Paused',
    'status.pending': 'Pending',
    'status.accepted': 'Accepted',
    'status.rejected': 'Rejected',
    
    // Forms
    'form.required': 'required',
    'form.title': 'Title',
    'form.description': 'Description',
    'form.budget.min': 'Minimum budget',
    'form.budget.max': 'Maximum budget',
    'form.timeline': 'Expected timeline',
    'form.complexity': 'Complexity',
    'form.skills': 'Required skills',
    
    // Messages
    'msg.success': 'Success',
    'msg.error': 'Error',
    'msg.loading': 'Loading...',
    'msg.no.results': 'No results found',
    
    // Time
    'time.today': 'today',
    'time.day': 'd',
    'time.week': 'w',
    'time.ago': 'ago',
    
    // Messages
    'messages.loading': 'Loading messages...',
    'messages.login.required': 'You must be logged in',
    'messages.back': 'Back',
    'messages.conversations': 'Conversations',
    'messages.no.conversations': 'No conversations',
    'messages.anonymous.user': 'User',
    'messages.anonymous.developer': 'Developer',
    'messages.anonymous.client': 'Client',
    'messages.general.conversation': 'General conversation',
    'messages.accept': 'Accept',
    'messages.reject': 'Reject',
    'messages.ratings': 'reviews',
    'messages.rate': 'Rate',
    'messages.no.messages': 'No messages in this conversation',
    'messages.start.conversation': 'Start the discussion!',
    'messages.user': 'User',
    'messages.type.message': 'Type your message...',
    'messages.select.conversation': 'Select a conversation',
    'messages.select.conversation.desc': 'Choose a conversation to start chatting',
    'messages.application.accepted': 'Application accepted!',
    'messages.application.accepted.desc': 'Congratulations, your application has been accepted by the client.',
    'messages.application.rejected': 'Application rejected.',
    'messages.application.rejected.desc': 'Your application was not selected for this project.',
    'messages.application.accepted.success': 'Application accepted successfully!',
    'messages.application.rejected.success': 'Application rejected successfully!',
    
    // Dashboard
    'dashboard.not.rated.yet': 'Not yet rated',
    'dashboard.client.title': 'Client Dashboard',
    'dashboard.client.welcome': 'Welcome',
    'dashboard.client.subtitle': 'Manage your projects and developers',
    'dashboard.refresh': 'Refresh',
    'dashboard.new.project': 'New Project',
    'dashboard.my.projects': 'My Projects',
    'dashboard.developers': 'Developers',
    'dashboard.conversations': 'Conversations',
    'dashboard.active.projects': 'Active Projects',
    'dashboard.view.all': 'View all',
    'dashboard.no.projects': 'No projects created',
    'dashboard.no.projects.desc': 'Create your first project to start collaborating with developers',
    'dashboard.create.first.project': 'Create my first project',
    'dashboard.view.project': 'View project',
    'dashboard.edit': 'Edit',
    'dashboard.collaborating.developers': 'Collaborating Developers',
    'dashboard.no.developers': 'No developers assigned',
    'dashboard.no.developers.desc': 'Start collaborating with developers by creating a project',
    'dashboard.explore.developers': 'Explore developers',
    'dashboard.developer': 'Developer',
    'dashboard.years.experience': 'years of experience',
    'dashboard.day': 'day',
    'dashboard.hour': 'hour',
    'dashboard.unread.messages': 'unread message',
    'dashboard.profile': 'Profile',
    'dashboard.contact': 'Contact',
    'dashboard.need.help': 'Need help?',
    'dashboard.need.help.desc': 'Explore our platform to find the best developers or manage your existing projects',
    'dashboard.manage.projects': 'Manage my projects',
    'dashboard.my.conversations': 'My conversations',
    'dashboard.budget.negotiate': 'Budget to negotiate',
    
    // Dashboard Developer
    'dashboard.developer.title': 'Developer Dashboard',
    'dashboard.developer.welcome': 'Welcome',
    'dashboard.developer.subtitle': 'Manage your projects and applications',
    'dashboard.explore.projects': 'Explore Projects',
    'dashboard.my.public.profile': 'My Public Profile',
    'dashboard.applications': 'Applications',
    'dashboard.rating': 'Average Rating',
    'dashboard.assigned.projects': 'Assigned Projects',
    'dashboard.no.assigned.projects': 'No assigned projects',
    'dashboard.no.assigned.projects.desc': 'Apply to projects to start collaborating with clients',
    'dashboard.find.projects': 'Find projects',
    'dashboard.assigned': 'Assigned',
    'dashboard.created': 'Created',
    'dashboard.my.applications': 'My Applications',
    'dashboard.no.applications': 'No applications',
    'dashboard.no.applications.desc': 'Start applying to projects that interest you',
    'dashboard.view.available.projects': 'View available projects',
    'dashboard.untitled.project': 'Untitled project',
    'dashboard.no.description': 'No description',
    'dashboard.applied.on': 'Applied on',
    'dashboard.develop.career': 'Develop your career!',
    'dashboard.develop.career.desc': 'Explore new projects, develop your skills and build your reputation',
    'dashboard.edit.profile': 'Edit my profile',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.preparing.data': 'Preparing your data',
    'dashboard.loading.error': 'Loading error',
    'dashboard.retry': 'Retry',
    'dashboard.access.denied': 'Access denied',
    'dashboard.redirecting': 'Redirecting...',
    'dashboard.unknown.date': 'Unknown date',
    'dashboard.invalid.date': 'Invalid date',
    
    // Developer profile pages
    'profile.developer.not.found': 'Profile not found',
    'profile.developer.back.to.developers': 'Back to developers',
    'profile.developer.back': 'Back',
    'profile.developer.loading': 'Loading profile...',
    'profile.developer.daily.rate': '/day',
    'profile.developer.hourly.rate': '/h',
    'profile.developer.contact.info': 'Contact information',
    'profile.developer.location': 'Location',
    'profile.developer.email': 'Email',
    'profile.developer.phone': 'Phone',
    'profile.developer.website': 'Website',
    'profile.developer.experience': 'Experience',
    'profile.developer.experience.years': 'years of experience',
    'profile.developer.availability': 'Availability',
    'profile.developer.availability.available': 'Available',
    'profile.developer.availability.busy': 'Busy',
    'profile.developer.availability.unavailable': 'Unavailable',
    'profile.developer.timezone': 'Timezone',
    'profile.developer.actions': 'Actions',
    'profile.developer.contact': 'Contact',
    'profile.developer.rate': 'Rate',
    'profile.developer.edit.profile': 'Edit profile',
    'profile.developer.about': 'About',
    'profile.developer.no.description': 'No description available at the moment.',
    'profile.developer.skills': 'Skills',
    'profile.developer.no.skills': 'No skills listed at the moment.',
    'profile.developer.languages': 'Languages',
    'profile.developer.no.languages': 'No languages listed at the moment.',
    'profile.developer.portfolio': 'Portfolio & Links',
    'profile.developer.portfolio.github': 'GitHub',
    'profile.developer.portfolio.linkedin': 'LinkedIn',
    'profile.developer.portfolio.website': 'Personal website',
    'profile.developer.ratings.reviews': 'Reviews & Ratings',
    'profile.developer.ratings.average': 'Average rating',
    'profile.developer.ratings.total': 'reviews in total',
    'profile.developer.ratings.no.reviews': 'No reviews yet',
    'profile.developer.ratings.first.review': 'Be the first to leave a review!',
    'profile.developer.ratings.project': 'Project',
    'profile.developer.ratings.by': 'by',
    'profile.developer.ratings.anonymous': 'Anonymous client',
    
    // Project detail pages
    'project.detail.not.found': 'Project not found',
    'project.detail.not.found.desc': 'This project does not exist or has been deleted.',
    'project.detail.back.to.projects': 'Back to projects',
    'project.detail.title': 'Project Details',
    'project.detail.subtitle': 'Discover all the details of this project and apply if it matches your skills',
    'project.detail.change.status': 'Change status',
    'project.detail.type.automation': 'Automation',
    'project.detail.type.ai': 'Artificial Intelligence',
    'project.detail.type.chatbot': 'Chatbot',
    'project.detail.type.data_analysis': 'Data Analysis',
    'project.detail.type.other': 'Other',
    'project.detail.complexity.simple': 'Simple',
    'project.detail.complexity.medium': 'Medium',
    'project.detail.complexity.complex': 'Complex',
    'project.detail.client.info': 'Client information',
    'project.detail.client.anonymous': 'Anonymous client',
    'project.detail.client.company': 'Company',
    'project.detail.client.industry': 'Industry',
    'project.detail.client.company.size': 'Company size',
    'project.detail.client.website': 'Website',
    'project.detail.project.details': 'Project details',
    'project.detail.project.type': 'Project type',
    'project.detail.project.complexity': 'Complexity',
    'project.detail.project.status': 'Status',
    'project.detail.budget': 'Budget',
    'project.detail.timeline': 'Timeline',
    'project.detail.posted': 'Posted on',
    'project.detail.updated': 'Updated on',
    'project.detail.skills.required': 'Required skills',
    'project.detail.skills.no.requirements': 'No specific skills required',
    'project.detail.apply': 'Apply',
    'project.detail.apply.message': 'Application message',
    'project.detail.apply.message.placeholder': 'Introduce yourself and explain why you are the ideal candidate for this project...',
    'project.detail.apply.submit': 'Send my application',
    'project.detail.apply.success': 'Application sent successfully!',
    'project.detail.apply.already.applied': 'You have already applied',
    'project.detail.apply.already.applied.desc': 'You have already sent an application for this project.',
    'project.detail.apply.status.pending': 'Your application is pending response.',
    'project.detail.apply.status.accepted': 'Congratulations! Your application has been accepted.',
    'project.detail.apply.status.rejected': 'Your application has been rejected.',
    'project.detail.login.required': 'Login required',
    'project.detail.login.required.desc': 'You must log in to apply for this project.',
    'project.detail.login': 'Log in',
    'project.detail.client.only': 'For clients only',
    'project.detail.client.only.desc': 'Only developers can apply to projects.',
    'project.detail.own.project': 'Your project',
    'project.detail.own.project.desc': 'You cannot apply to your own project.',
    'project.detail.status.modal.title': 'Change project status',
    'project.detail.status.modal.current': 'Current status',
    'project.detail.status.modal.new': 'New status',
    'project.detail.status.modal.save': 'Update',
    'project.detail.status.modal.cancel': 'Cancel',
    'project.detail.status.open': 'Open',
    'project.detail.status.open.desc': 'The project is open for applications',
    'project.detail.status.in_progress': 'In Progress',
    'project.detail.status.in_progress.desc': 'The project is under development',
    'project.detail.status.completed': 'Completed',
    'project.detail.status.completed.desc': 'The project has been completed successfully',
    'project.detail.status.cancelled': 'Cancelled',
    'project.detail.status.cancelled.desc': 'The project has been cancelled',
    'project.detail.status.on_hold': 'On Hold',
    'project.detail.status.on_hold.desc': 'The project is temporarily on hold',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr')

  // Charger la langue depuis localStorage au démarrage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Sauvegarder la langue dans localStorage quand elle change
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  // Fonction de traduction
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 